# Capítulo 2 - WOOLDRIGDE 
### EXERCÍCIO COMPUTACIONAL 2

O Conjunto de dados do arquivo CEOSAL2 contém informações sobre CEOs de corporações norte-americanas. A variável salary é a compensação anual, em milhares de dólares e $####ceoten$ é o número prévio de anos como CEO da empresa.

i) Encontre o salário médio e a permanência média na amostra.

ii) Quantos CEOS estão em seu primeiro ano no cargo (isto é, ceoten=0)? Qual é a permanência mais longa como CEO? 

iii)Estime o modelo de regressNao simples: 

log(salary)=Bo + Bo*ceoten + u 

e registre seus resultados da forma usual. Qual é o aumento percentual previsto (aproximado) no salário quando se tem um ano a mais como CEO? 

In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [2]:
 df = pd.read_stata('ceosal2.dta')

In [3]:
df

salary  age  college  grad  comten  ceoten   sales  profits   mktval  \
0      1161   49        1     1       9       2  6200.0      966  23200.0   
1       600   43        1     1      10      10   283.0       48   1100.0   
2       379   51        1     1       9       3   169.0       40   1100.0   
3       651   55        1     0      22      22  1100.0      -54   1000.0   
4       497   44        1     1       8       6   351.0       28    387.0   
..      ...  ...      ...   ...     ...     ...     ...      ...      ...   
172     264   63        1     0      42       3   334.0       43    480.0   
173     185   58        1     0      39       1   766.0       49    560.0   
174     387   71        1     1      32      13   432.0       28    477.0   
175    2220   63        1     1      18      18   277.0      -80    540.0   
176     445   69        1     0      23       0   249.0       31    828.0   

      lsalary    lsales    lmktval  comtensq  ceotensq   profmarg  
0    7.057037  8.732305  10.051908        81         4  15.580646  
1    6.396930  5.645447   7.003066       100       100  16.961130  
2    5.937536  5.129899   7.003066        81         9  23.668638  
3    6.478509  7.003066   6.907755       484       484  -4.909091  
4    6.208590  5.860786   5.958425        64        36   7.977208  
..        ...       ...        ...       ...       ...        ...  
172  5.575949  5.811141   6.173786      1764         9  12.874251  
173  5.220356  6.641182   6.327937      1521         1   6.396867  
174  5.958425  6.068426   6.167517      1024       169   6.481482  
175  7.705263  5.624018   6.291569       324       324 -28.880867  
176  6.098074  5.517453   6.719013       529         0  12.449800  

[177 rows x 15 columns]

In [4]:
salario_medio = df['salary'].mean()
salario_medio

865.8644067796611

In [5]:
permanencia_media=df['ceoten'].mean()
permanencia_media

7.954802259887006

### Item i)

In [6]:
##i) 
print('O salário médio é de ' + str(salario_medio))
print('A permanência média é de' + str(permanencia_media))

O salário médio é de 865.8644067796611
A permanência média é de7.954802259887006


Aqui ordenamos a base de dados na variável CEOTEN pois assim podemos visualizar quantos CEOS estão no seu primeiro ano do cargo e depois qual a permanência mais longa 

In [7]:
ordenacao=df.sort_values(by='ceoten',ascending=True).reset_index()
ordenacao[0:6]

index  salary  age  college  grad  comten  ceoten   sales  profits  mktval  \
0    176     445   69        1     0      23       0   249.0       31   828.0   
1    169     467   49        1     1      13       0   513.0       49   534.0   
2     84     462   58        1     1      23       0  1400.0       50   769.0   
3    136     345   54        1     1      33       0   994.0       56   781.0   
4    128     834   61        1     1      32       0  7600.0      364  5300.0   
5     47     449   56        1     0      31       1   661.0       37   538.0   

    lsalary    lsales   lmktval  comtensq  ceotensq   profmarg  
0  6.098074  5.517453  6.719013       529         0  12.449800  
1  6.146329  6.240276  6.280396       169         0   9.551657  
2  6.135565  7.244227  6.645091       529         0   3.571429  
3  5.843544  6.901737  6.660575      1089         0   5.633803  
4  6.726233  8.935904  8.575462      1024         0   4.789474  
5  6.107023  6.493754  6.287858       961         1   5.597579

In [8]:
df.sort_values(by='ceoten',ascending=False)

salary  age  college  grad  comten  ceoten   sales  profits  mktval  \
120     790   69        1     0      45      37  1200.0      140  3200.0   
12     1200   72        1     0      37      37   796.0       35   678.0   
135     853   58        1     0      34      34   818.0       33   411.0   
121     396   80        1     0      58      28   513.0       53   963.0   
29      300   77        0     0      45      26  6900.0      483  4700.0   
..      ...  ...      ...   ...     ...     ...     ...      ...     ...   
136     345   54        1     1      33       0   994.0       56   781.0   
84      462   58        1     1      23       0  1400.0       50   769.0   
169     467   49        1     1      13       0   513.0       49   534.0   
128     834   61        1     1      32       0  7600.0      364  5300.0   
176     445   69        1     0      23       0   249.0       31   828.0   

      lsalary    lsales   lmktval  comtensq  ceotensq   profmarg  
120  6.672033  7.090077  8.070906      2025      1369  11.666667  
12   7.090077  6.679599  6.519147      1369      1369   4.396985  
135  6.748760  6.706862  6.018593      1156      1156   4.034230  
121  5.981414  6.240276  6.870053      3364       784  10.331384  
29   5.703783  8.839276  8.455317      2025       676   7.000000  
..        ...       ...       ...       ...       ...        ...  
136  5.843544  6.901737  6.660575      1089         0   5.633803  
84   6.135565  7.244227  6.645091       529         0   3.571429  
169  6.146329  6.240276  6.280396       169         0   9.551657  
128  6.726233  8.935904  8.575462      1024         0   4.789474  
176  6.098074  5.517453  6.719013       529         0  12.449800  

[177 rows x 15 columns]

### item ii)

In [9]:
numero_ceos_0=[]
for i in range(0,len(df)):
    if df['ceoten'][i]==0:
        numero_ceos_0.append(i)
print('o numero de CEOS no primeiro ano é ' + str(len(numero_ceos_0)) )       

o numero de CEOS no primeiro ano é 5


In [10]:
print('A maior permanência é de 37 anos')

A maior permanência é de 37 anos


Carregando variáveis para a regressão

In [11]:
y=df['lsalary']
X=df['ceoten']

Estimando a regressão 

In [12]:
# é necessário adicionar uma constante a matriz X
X_sm = sm.add_constant(X)
# OLS vem de Ordinary Least Squares e o método fit irá treinar o modelo
results = sm.OLS(y, X_sm).fit()
# mostrando as estatísticas do modelo
results.summary()
# mostrando as previsões para o mesmo conjunto passado
results.predict(X_sm)
results.summary()

/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                lsalary   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                  0.008
Method:                 Least Squares   F-statistic:                     2.334
Date:                Wed, 11 Mar 2020   Prob (F-statistic):              0.128
Time:                        23:37:57   Log-Likelihood:                -160.84
No. Observations:                 177   AIC:                             325.7
Df Residuals:                     175   BIC:                             332.0
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.5055      0.068     95.682      0.000       6.371       6.640
ceoten         0.0097      0.006      1.528      0.128      -0.003       0.022
==============================================================================
Omnibus:                        3.858   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.145   Jarque-Bera (JB):                3.907
Skew:                          -0.189   Prob(JB):                        0.142
Kurtosis:                       3.622   Cond. No.                         16.1
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### item iii)

In [13]:
print('O aumento percentual previsto no salário quando se tem um ano a mais como CEO é de 0.0097')

O aumento percentual previsto no salário quando se tem um ano a mais como CEO é de 0.0097


# Capitulo 3 - WOOLDRIGDE 

### Exercício Computacional 2

Use os dados do arquivo HPRICE1 para estimar o modelo

price= Bo + B1*sqrft + B2*bdrms + u 

Em que price é o preço da residência medido em milhares de dólares.

i) Escreva os resultados em forma de equação; 

ii) Qual é o aumento estimado do preço de uma casa com um quarto a mais, mantendo a área constante?

iii) Qual é o aumento estimado do preço de uma casa com um quarto adicional de 140 pés quadrados? Compare isso com sua resposta do item ii)

iv) Qual porcentagem de variação do preço é explicada pela área e número de quartos?

v) A primeira casa da amostra tem sqrft=2.438 e bdrms=4. Encontre o preço de venda previsto dessa casa a partir da linha de regressão MQO. 

vi) O preço de venda real da primeira casa da amostra foi de US$ 300.000 (assim, price = 3000). Encontre o resíduo para essa casa. o Valor sugere que o comprador pagou pouco ou muito pela casa? 


In [4]:
df2=pd.read_stata('hprice1.dta')
df2

price      assess  bdrms  lotsize  sqrft  colonial    lprice   lassess  \
0   300.0  349.100006      4   6126.0   2438         1  5.703783  5.855359   
1   370.0  351.500000      3   9903.0   2076         1  5.913503  5.862210   
2   191.0  217.699997      3   5200.0   1374         0  5.252274  5.383118   
3   195.0  231.800003      3   4600.0   1448         1  5.273000  5.445875   
4   373.0  319.100006      4   6095.0   2514         1  5.921578  5.765504   
..    ...         ...    ...      ...    ...       ...       ...       ...   
83  295.0  318.299988      3   6056.0   1837         1  5.686975  5.762994   
84  236.0  259.399994      3   5828.0   1715         0  5.463832  5.558371   
85  202.5  258.100006      3   6341.0   1574         0  5.310740  5.553347   
86  219.0  232.000000      2   6362.0   1185         0  5.389072  5.446737   
87  242.0  252.000000      4   4950.0   1774         1  5.488938  5.529429   

    llotsize    lsqrft  
0   8.720297  7.798934  
1   9.200593  7.638198  
2   8.556414  7.225482  
3   8.433811  7.277938  
4   8.715224  7.829630  
..       ...       ...  
83  8.708805  7.515889  
84  8.670429  7.447168  
85  8.754792  7.361375  
86  8.758098  7.077498  
87  8.507143  7.480992  

[88 rows x 10 columns]

In [5]:
from pandas import DataFrame
from sklearn import linear_model
import statsmodels.api as sm



X = df2[['sqrft','bdrms']] # here we have 2 variables for multiple regression. If you just want to use one variable for simple linear regression, then use X = df['Interest_Rate'] for example.Alternatively, you may add additional variables within the brackets
Y = df2['price']
 
# with sklearn
regr = linear_model.LinearRegression()
regr.fit(X, Y)

print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

# prediction with sklearn
#New_Interest_Rate = 2.75
#New_Unemployment_Rate = 5.3
#print ('Predicted Stock Index Price: \n', regr.predict([[New_Interest_Rate ,New_Unemployment_Rate]]))

# with statsmodels
X = sm.add_constant(X) # adding a constant
 
model = sm.OLS(Y, X).fit()
predictions = model.predict(X) 
 
print_model = model.summary()
print(print_model)

Intercept: 
 -19.314995765184904
Coefficients: 
 [ 0.12843621 15.19819097]
                            OLS Regression Results                            
Dep. Variable:                  price   R-squared:                       0.632
Model:                            OLS   Adj. R-squared:                  0.623
Method:                 Least Squares   F-statistic:                     72.96
Date:                Sun, 05 Apr 2020   Prob (F-statistic):           3.57e-19
Time:                        09:46:22   Log-Likelihood:                -488.00
No. Observations:                  88   AIC:                             982.0
Df Residuals:                      85   BIC:                             989.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------

/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)
/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


### item i) 

In [16]:
print('price =' + str(regr.intercept_) + ' + ' + str( regr.coef_[0])+'*sqrt' + ' + ' + str(regr.coef_[1]) +'*bdrms')

price =-19.314995765184904 + 0.12843621036829206*sqrt + 15.198190967822047*bdrms


### item ii) 

In [17]:
print('O aumento esperado no preço de um quarto a mais mantendo a área constante é de ' + str(regr.coef_[1]) + ' dólares')

O aumento esperado no preço de um quarto a mais mantendo a área constante é de 15.198190967822047 dólares


### item iii) 

In [25]:
quarto_140=regr.coef_[0]*140 + regr.coef_[1]

In [27]:
print('O aumento esperado no preço de um quarto adicional de 140 pés quadrados é de ' + str(quarto_140) + ' dólares')
print('Como há aumento do tamanho da casa, o efeito considerado é maior')

O aumento esperado no preço de um quarto adicional de 140 pés quadrados é de 33.179260419382935 dólares
Como há aumento do tamanho da casa, o efeito considerado é maior


### item iv) 

In [28]:
print('A porcentagem de variação do preço explicada pelas duas variáveis é de 63.2')

A porcentagem de variação do preço explicada pelas duas variáveis é de 63.2


### item v) 

In [21]:
sqrt=2438
bdrms=4 
preco= regr.intercept_ + sqrt*regr.coef_[0] + bdrms*regr.coef_[1]
print('Preço estimado (US$): ' + str(preco))

Preço estimado (US$): 354.60524898399933


### item vi)

In [23]:
residuo=300-preco
print('Logo, o resíduo para esta casa é de ' + str(residuo) + ' sugerindo que o comprador pagou barato no preço da casa')

Logo, o resíduo para esta casa é de -54.60524898399933 sugerindo que o comprador pagou barato no preço da casa
